# Project information
site_name: Nuestro Manual
site_author: 23people.io
site_description: El manual público de lo que hacemos en 23people como empresa y equipo de profesionales TI
strict: false
site_url: https://23people.io/

# Repository
repo_name: 23people/handbook
repo_url: https://github.com/23people-io/23p-handbook
edit_uri: edit/main/docs/

# Copyright
copyright: Copyright &copy; 2025 <a href="https://23people.io">23people SpA</a>

# Configuration
docs_dir: "docs"
site_dir: "site"
theme:
  name: "material"
  palette:
    - media: "(prefers-color-scheme)"
      scheme: default
      primary: pink
      accent: pink
      toggle:
        icon: material/lightbulb
        name: "Switch to light mode"
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: pink
      accent: pink
      toggle:
        icon: material/lightbulb-outline
        name: "Switch to dark mode"
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: pink
      accent: pink
      toggle:
        icon: material/lightbulb-auto-outline
        name: "Switch to system preference"
  features:
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
    - content.action.view
    - announce.dismiss
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.instant
    - navigation.instant.progress
    - navigation.path
    - navigation.prune
    - navigation.top
    - navigation.tracking
    - navigation.sections
    - navigation.indexes
    - search.suggest
    - search.share
    - toc.follow
  font:
    text: Roboto
    code: Roboto Mono
  logo: "https://23people.io/img/logo-white.svg"
  icon:
    repo: fontawesome/brands/github
  language: es

# Plugins
plugins:
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - "mkdocs-version-annotations":
      version_added_admonition: "tip"
  - mkdocstrings:
      enable_inventory: true
      handlers:
        python:
          options:
            docstring_style: google
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
  - git-committers:
      repository: 23people-io/23p-handbook
      branch: main
      token: !ENV ["MKDOCS_GIT_COMMITTERS_APIKEY"]

markdown_extensions:
  - pymdownx.highlight:
      linenums: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.snippets:
      restrict_base_path: false
  - admonition
  - tables
  - toc:
      permalink: true
      toc_depth: 2
  - attr_list
  - pymdownx.arithmatex:
      generic: true
  - def_list

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - _assets/stylesheets/extra.css

extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/23people-io
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/9192215
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/23people.io/
    - icon: fontawesome/brands/tiktok
      link: https://www.tiktok.com/@23people.io
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/23people
  chatbot:
    url: https://2prxfnwkygf4vexczrbpcq.streamlit.app/?embed=true

nav:
  - "Hello there.":
      - index.md      

      - "Quienes somos":
          - about-us/who-we-are/index.md
          - Valores: about-us/who-we-are/values.md
          - Principios: principles/index.md
          - Prácticas: practices/index.md
          - Partnerships: about-us/who-we-are/partnerships.md
          - Historia: about-us/who-we-are/history.md
          - Nombre: about-us/who-we-are/name.md

      - "Lo que hacemos":
          - about-us/what-we-do/index.md
          - Desafíos: about-us/what-we-do/challenges.md
          - Servicios: about-us/what-we-do/services.md

      - "Lo que nos diferencia":
          - about-us/how-we-work/index.md
          - Especialización en Roles Tech: about-us/how-we-work/tech-roles.md
          - Optimización en Reclutamiento Tech: about-us/how-we-work/talent-recruitment.md
          - Madures de desarrollo de software: about-us/how-we-work/methodology.md
          - Manejo de tecnologías empresariales y emergentes: about-us/how-we-work/stack.md
          - Satisfacción de clientes: about-us/how-we-work/customer-success.md

      - "Lo que perseguimos":
          - about-us/what-we-pursue/index.md
          - Metas: about-us/what-we-pursue/goals.md
          - Principios: about-us/what-we-pursue/principles.md

      # FIXME: Figure out how to show raw markdown files in the nav
      - "LLM Resources": 
          - handbook-summary.md: llm-resources/handbook-summary.md

  - "Comunidad":
      - Beneficios:
          - community/benefits/index.md
          - Convenios:
              - Betterfly: community/benefits/agreements/betterfly.md
              - Banco de Chile: community/benefits/agreements/cuenta-bancaria-banco-de-chile.md
              - Seguros Complementarios: community/benefits/agreements/seguros-complementarios.md
          - Incentivos:
              - Vacaciones: community/benefits/incentives/vacaciones.md
              - Regalo de Cumpleaños: community/benefits/incentives/regalo-cumpleanios.md
              - Fiestas Patrias y Navidad: community/benefits/incentives/fiestas-patrias-y-navidad.md
              - Dia Libre Cumpleaños: community/benefits/incentives/dia-libre-cunpleanios.md
              - Baby Shower: community/benefits/incentives/baby-shower.md
          - Reembolsos:
              - Vacunación contra la influenza: community/benefits/refunds/vacunacion-influenza.md
              - Cursos: community/benefits/refunds/cursos.md
              - Certificaciones Internacionales: community/benefits/refunds/certificaciones-internacionales.md
              - Mejora de Espacio de Trabajo: community/benefits/refunds/mejora-espacio-de-trabajo.md
          - Capacitaciones:
              - Cursos de Ingles: community/benefits/trainings/clases-de-ingles.md
      - Procedimientos:
          - Administrativos: community/procedures/administratives.md
          - Servidor de Discord: community/procedures/discord-server.md
      - Eventos:
          - community/events/index.md
      - Entretención:
          - Playlist Spotify: community/spotify-playlist.md

  - "Organización":
      - organization/index.md
      - "Cargos y Roles": organization/tribes/iarvis-tribe/workforce/index.md
      - "Equipos":
          - organization/teams/index.md
          - "Tech Talent Services (TTS)":
              - "Resumen": organization/teams/tech-talent-services/index.md
              - "Glosario": organization/teams/tech-talent-services/glossary.md
          - "Sales & Growth Marketing (SMKT)":
              - "Resumen": organization/teams/sales-and-growth-marketing/index.md
              - "Glosario": organization/teams/sales-and-growth-marketing/glossary.md
          - "Backoffice (BKO)":
              - "Resumen": organization/teams/backoffice/index.md
              - "Glosario": organization/teams/backoffice/glossary.md
              - "Sello de Calidad": organization/teams/backoffice/quality-seal.md
          - "Research & Development (R&D)": organization/teams/research-and-development/index.md
      - "Tribus":
          - organization/tribes/index.md
          - "Iarvis Tribe": organization/tribes/iarvis-tribe/index.md
          - "Drakkar Tribe": organization/tribes/drakkar-tribe/index.md

  - "Principios":
      - principles/index.md
      - People First: principles/people-first.md
      - Sustentabilidad: principles/sustainability.md
      - Transparencia: principles/transparency.md
      - Equidad: principles/egalitarian.md
      - Agilidad: principles/agility.md

  - "Prácticas":
      - practices/index.md
      - "Gestionar el trabajo, no las personas": practices/manage-work-not-people.md
      - "Todo es un servicio a otros": practices/everything-is-a-service.md
      - "Comunicación asincrónica": practices/asynchronous-communication.md
      - "Escribir, luego comunicar": practices//write-then-communicate.md
      - "Estructurar la narrativa": practices/structure-the-narrative.md
      - "Notificar los avances": practices/notify-progress.md
      - "Uso de Claude Projects": practices/using-claude-projects.md

  - "Insights":
      - insights/index.md
      - "La Evolución Digital Empresarial": insights/business-digital-evolution.md
      - "Recursión como predictor de desempeño en desarrolladores": insights/recursion-as-a-good-predictor-for-developers.md
      - "Autonomía de Equipos, APIs y Servicios": insights/team-autonomy-through-service-apis.md
      - "IA como Multiplicador de Capacidades": insights/ai-as-professional-capabilities-multiplier.md

  - "Sustentabilidad":
      - "Nuestro Compromiso": sustainability/our-commitment.md
      - "Estrategia Reducción Emisiones": sustainability/strategy.md
      - "Equipo de Sustentabilidad": sustainability/team.md
      - "Recomendaciones de Tecnología": sustainability/technology-recommendations.md

  - "Guía Técnica":
      - technical-guide/index.md
      - "Desarrollo de Software": technical-guide/software-development/index.md
      - "Principios de Desarrollo de Software": technical-guide/software-development/principles.md
      - "Metodologías de Desarrollo de Software": technical-guide/software-development/methodologies.md
      - "Tecnologías de Desarrollo de Software": technical-guide/software-development/technologies.md
      - "Prácticas de Desarrollo de Software": technical-guide/software-development/practices.md
      - "IA y Machine Learning": technical-guide/software-development/ai-and-machine-learning.md
      - Cloud: technical-guide/software-development/cloud.md
      - Seguridad: technical-guide/software-development/security.md

not_in_nav: |
  /llm-resources/handbook-summary.md