# Project information
site_name: Nuestro Manual
site_author: 23people.io
site_description: El Manual público de lo que hacemos en 23people
strict: false
site_url: https://23people.io/

# Repository
repo_name: 23people/handbook
repo_url: https://github.com/23people-io/23people-handbook
edit_uri: edit/main/docs/

# Copyright
copyright: Copyright &copy; 2024 <a href="https://23people.io">23people SpA</a>

# Configuration
docs_dir: "docs"
site_dir: "site"
theme:
  name: "material"
  override:
  palette:
    - media: "(prefers-color-scheme)"
      scheme: default
      primary: pink
      accent: pink
      toggle:
        icon: material/lightbulb
        name: "Switch to light mode"
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: pink
      accent: pink
      toggle:
        icon: material/lightbulb-outline
        name: "Switch to dark mode"
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: pink
      accent: pink
      toggle:
        icon: material/lightbulb-auto-outline
        name: "Switch to system preference"
  features:
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
    - content.action.view
    - announce.dismiss
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.instant
    - navigation.instant.progress
    - navigation.path
    - navigation.prune
    - navigation.top
    - navigation.tracking
    - navigation.sections
    - navigation.indexes
    - search.suggest
    - search.share
    - toc.follow
  font:
    text: Roboto
    code: Roboto Mono
  logo: "https://23people.io/img/logo-white.svg"
  icon:
    repo: fontawesome/brands/github
  language: es

# Plugins
plugins:
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - "mkdocs-version-annotations":
      version_added_admonition: "tip"
  - mkdocstrings:
      enable_inventory: true
      handlers:
        python:
          options:
            docstring_style: google
  # - git-revision-date-localized:
  #     enable_creation_date: true
  #     type: timeago
  # - git-committers:
  #     repository: 23people-io/23people-handbook
  #     branch: main
  #     token: !ENV ["MKDOCS_GIT_COMMITTERS_APIKEY"]

markdown_extensions:
  - pymdownx.highlight:
      linenums: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.snippets:
      restrict_base_path: false
  - admonition
  - tables
  - toc:
      permalink: true
      toc_depth: 2
  - attr_list
  - pymdownx.arithmatex:
      generic: true
  - def_list

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - _assets/stylesheets/extra.css

extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/23people-io
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/9192215
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/23people.io/
    - icon: fontawesome/brands/tiktok
      link: https://www.tiktok.com/@23people.io
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/23people
  chatbot:
    url: https://2prxfnwkygf4vexczrbpcq.streamlit.app/?embed=true
  extra:
    status:
      do_no_index: This page will not be indexed in vector stores

nav:
  - "Hello there.":
      - index.md
      - "Lo que hacemos":
          - about-us/what-we-do/index.md
          - Desafíos: about-us/what-we-do/challenges.md
          - Servicios: about-us/what-we-do/services.md
          - Clientes: about-us/about-us/what-we-do/clients.md
          - Casos de éxito: about-us/what-we-do/success-stories.md
      - "Lo que nos diferencia":
          - about-us/how-we-work/index.md
          - Especialización en Roles Tech: about-us/how-we-work/tech-roles.md
          - Optimización en Reclutamiento Tech: about-us/how-we-work/talent-recruitment.md
          - Madures de desarrollo de software: about-us/how-we-work/methodology.md
          - Manejo de tecnologías empresariales y emergentes: about-us/how-we-work/stack.md
          - Satisfacción de clientes: about-us/how-we-work/customer-success.md
      - "Lo que perseguimos":
          - about-us/what-we-pursue/index.md
          - Metas: about-us/what-we-pursue/goals.md
          - Principios: about-us/what-we-pursue/principles.md

  - Comunidad:
      - Beneficios: community/benefits/index.md
      - Eventos: community/events/index.md
      - Playlist Spotify: community/spotify-playlist.md
      - Procedimientos:
          - Administrativos: community/procedures/administratives.md
          - Servidor de Discord: community/procedures/discord-server.md

  - Organización:
      - Estructura general: organization/index.md
      - Cargos y Roles: organization/tribes/iarvis-tribe/workforce/index.md
      - Equipos:
          - "Tech Talent Services (TTS)":
              - "Resumen": organization/teams/tech-talent-services/index.md
              - "Glosario": organization/teams/tech-talent-services/glossary.md
          - "Sales & Growth Marketing (SMKT)":
              - "Resumen": organization/teams/sales-and-growth-marketing/index.md
              - "Glosario": organization/teams/sales-and-growth-marketing/glossary.md
          - "Backoffice (BKO)":
              - "Resumen": organization/teams/backoffice/index.md
              - "Glosario": organization/teams/backoffice/glossary.md
          - "Research & Development (R&D)": organization/teams/research-and-development/index.md

  - Prácticas:
      - Resúmen: culture/practices/index.md
      - "Gestionar el trabajo, no las personas": culture/practices/manage-work-not-people.md
      - "Todo es un servicio a otros": culture/practices/everything-is-a-service.md
      - "Comunicación asincrónica": culture/practices/asynchronous-communication.md
      - "Escribir, luego comunicar": culture/practices//write-then-communicate.md
      - "Estructurar la narrativa": culture/practices/structure-the-narrative.md
      - "Notificar los avances": culture/practices/notify-progress.md

  # - Insights:
  #     - insights/index.md
  #     - La Evolución Digital Empresarial: insights/evolucion-digital-empresarial.md
  #     - Autonomía de Equipos, APIs y Servicios: insights/autonomia-equipos-api-servicios.md
  #     - Los Datos no tienen valor intrínseco: insights/datos-no-tienen-valor-intrinseco.md
  #     - IA Generativa como conector entre Humanos y Sistemas: insights/ia-generativa-conector-humanos-sistemas.md

  - Acerca del Manual:
      - the-handbook/index.md
      - Contribuir: the-handbook/contribute.md
