# Project information
site_name: Nuestro Manual
site_author: 23people.io
site_description: El Manual público de lo que hacemos en 23people
strict: false
site_url: https://23people.io/

# Repository
repo_name: 23people/handbook
repo_url: https://github.com/23people-io/23people-handbook
edit_uri: edit/main/docs/

# Copyright
copyright: Copyright &copy; 2024 <a href="https://23people.io">23people SpA</a>

# Configuration
docs_dir: "src/docs"
site_dir: "build/site"
theme:
  name: "material"
  palette:
    - media: "(prefers-color-scheme)"
      scheme: default
      primary: pink
      accent: pink
      toggle:
        icon: material/lightbulb
        name: "Switch to light mode"
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: pink
      accent: pink
      toggle:
        icon: material/lightbulb-outline
        name: "Switch to dark mode"
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: pink
      accent: pink
      toggle:
        icon: material/lightbulb-auto-outline
        name: "Switch to system preference"
  features:
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
    - announce.dismiss
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
    - navigation.instant.progress
    - navigation.path
    - navigation.indexes
    - navigation.top
    - navigation.tracking
    - navigation.sections
    - search.suggest
    - search.share
    - toc.follow
    - content.action.view
  font:
    text: Roboto
    code: Roboto Mono
  logo: "https://23people.io/img/logo-white.svg"
  icon:
    repo: fontawesome/brands/github
  language: es

# Plugins
plugins:
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - "mkdocs-version-annotations":
      version_added_admonition: "tip"
  - mkdocstrings:
      enable_inventory: true
      handlers:
        python:
          options:
            docstring_style: google
  # - git-revision-date-localized:
  #     enable_creation_date: true
  #     type: timeago
  # - git-committers:
  #     repository: 23people-io/23people-handbook
  #     branch: main
  #     token: !ENV ["MKDOCS_GIT_COMMITTERS_APIKEY"]

markdown_extensions:
  - pymdownx.highlight:
      linenums: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
            - name: mermaid
              class: mermaid
              format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.snippets:
      restrict_base_path: false
  - admonition
  - tables
  - toc:
      permalink: true
      toc_depth: 2
  - attr_list
  - pymdownx.arithmatex:
      generic: true
  - def_list

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/23people-io
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/9192215
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/23people.io/
    - icon: fontawesome/brands/tiktok
      link: https://www.tiktok.com/@23people.io
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/23people
  chatbot:
    url: https://2prxfnwkygf4vexczrbpcq.streamlit.app/?embed=true

nav:
  - "Inicio":
      - Bienvenidos a 23people: index.md
      - Lo que hacemos: 
          - what-we-do/index.md
          - Servicios: what-we-do/services.md              
          - Casos de Éxito: what-we-do/success-stories.md
      - Como lo hacemos:
            - how-we-do-it/index.md
            - Foco en Roles Tech: how-we-do-it/tech-roles.md
            - Reclutamiento de Tech Talent: how-we-do-it/talent-recruitment.md
            - Metodología de Desarrollo de Software: how-we-do-it/methodology.md
            - Stack Tecnológico: how-we-do-it/stack.md
            - Satisfacción de Clientes: how-we-do-it/customer-success.md
      - Estrategia: 
          - strategy/index.md
          - Metas: strategy/goals.md      
      - Organización: 
          - organization/index.md
          - Equipos:
              - organization/teams/index.md
              - "Tech Talent Services (TTS)": organization/teams/tech-talent-services/index.md
              - "Sales & Growth Marketing (SGM)": organization/teams/sales-and-growth-marketing/index.md
              - "Backoffice (BKO)": organization/teams/backoffice/index.md
              - "Research & Development (R&D)": organization/teams/research-and-development/index.md
          - Cargos y Roles Generales: organization/positions-and-roles/index.md
      - Historia: 
          - history/index.md      

  - Comunidad:
      - community/index.md
      - Beneficios: community/benefits/index.md
      - Procedimientos Administrativos: community/administrative-procedures/index.md
      - Eventos: community/events/index.md 
      - Playlist Spotify: community/spotify-playlist.md
      - Código de Conducta: community/code-of-conduct.md

  - Cultura:
      - culture/index.md
      - Valores: culture/values.md
      - Prácticas: 
          - culture/practices/index.md

  - Insights:
      - insights/index.md
      - La Evolución Digital Empresarial: insights/evolucion-digital-empresarial.md
      - Autonomía de Equipos, APIs y Servicios: insights/autonomia-equipos-api-servicios.md
      - Los Datos no tienen valor intrínseco: insights/datos-no-tienen-valor-intrinseco.md
      - IA Generativa como conector entre Humanos y Sistemas: insights/ia-generativa-conector-humanos-sistemas.md
      - Jerarquía de Contribución del Trabajo: insights/jerarquia-contribucion-del-trabajo.md
      - Jerarquía de Conceptos Organizacionales: insights/jerarquia-conceptos-organizacionales.md
      - Relación entre un SRM y un SDM: insights/relacion-entre-srm-sdm.md


  - Acerca del Manual: 
      - the-handbook/index.md
      - Contribuir: the-handbook/contribute.md
