# Project information
site_name: Nuestro Manual
site_author: 23people.io
site_description: Nuestro manual público de lo que hacemos en 23people
strict: false
site_url: https://23people.io/
site_favicon: https://23people.io/img/favicon.ico

# Repository
repo_name: 23people/handbook
repo_url: https://github.com/23people-io/23people-handbook
edit_uri: edit/main/docs/

# Copyright
copyright: Copyright &copy; 2024 <a href="https://23people.io">23people SpA</a>

# Configuration
docs_dir: "docs"
site_dir: "site"
theme:
  name: "material"
  palette:
    - media: "(prefers-color-scheme)"
      scheme: default
      primary: pink
      accent: pink
      toggle:
        icon: material/lightbulb
        name: "Switch to light mode"
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: pink
      accent: pink
      toggle:
        icon: material/lightbulb-outline
        name: "Switch to dark mode"
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: pink
      accent: pink
      toggle:
        icon: material/lightbulb-auto-outline
        name: "Switch to system preference"
  features:
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
    - announce.dismiss
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
    - navigation.instant.progress
    - navigation.path
    - navigation.indexes
    - navigation.top
    - navigation.tracking
    - navigation.sections
    - search.suggest
    - search.share
    - toc.follow
    - content.action.view
  font:
    text: Roboto
    code: Roboto Mono
  logo: "https://23people.io/img/logo-white.svg"
  icon:
    repo: fontawesome/brands/github
  language: es

# Plugins
plugins:
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - "mkdocs-version-annotations":
      version_added_admonition: "tip"
  - mkdocstrings:
      enable_inventory: true
      handlers:
        python:
          options:
            docstring_style: google
  # - git-revision-date-localized:
  #     enable_creation_date: true
  #     type: timeago
  # - git-committers:
  #     repository: 23people-io/23people-handbook
  #     branch: main
  #     token: !ENV ["MKDOCS_GIT_COMMITTERS_APIKEY"]

markdown_extensions:
  - pymdownx.highlight:
      linenums: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
            - name: mermaid
              class: mermaid
              format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.snippets:
      restrict_base_path: false
  - admonition
  - tables
  - toc:
      permalink: true
      toc_depth: 2
  - attr_list
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/23people-io
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/9192215
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/23people.io/
    - icon: fontawesome/brands/tiktok
      link: https://www.tiktok.com/@23people.io
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/23people
  chatbot:
    url: https://2prxfnwkygf4vexczrbpcq.streamlit.app/?embed=true

nav:
  - "Inicio":
      - Bienvenidos a 23people: index.md
      - Lo que hacemos: 
          - what-we-do/index.md
          - Servicios: what-we-do/services.md
          - Stack de Tecnologías: what-we-do/tech-stack.md
          - Roles TI: what-we-do/it-roles.md
          - Casos de Éxito: what-we-do/success-stories.md
      - Estrategia: 
          - strategy/index.md
          - Metas: strategy/goals.md
          - Objetivos: strategy/objectives.md
      - Cultura:
          - culture/index.md
          - Valores: culture/values.md
          - Prácticas: culture/index.md
          - Métricas: culture/metrics.md
      - Organización: 
          - organization/index.md
          - Equipos Operacionales:
              - organization/teams/index.md
              - "IT Talent Services (ITTS)": organization/teams/it-talent-services/index.md
              - "Growth Marketing & Sales (GMS)": organization/teams/growth-marketing-and-sales/index.md
              - "Backoffice (BKO)": organization/teams/backoffice/index.md
              - "Research & Development (R&D)": organization/teams/research-and-development/index.md
          - Interacciones: 
              - organization/interactions/index.md
          - Roles: 
              - organization/roles/index.md
              - "Operations Director": organization/roles/operations-director.md
              - "Service Delivery Manager": organization/roles/service-delivery-manager.md
              - "Service Request Manager": organization/roles/service-request-manager.md
              - "Key Account Manager": organization/roles/key-account-manager.md
      - Historia: 
          - history/index.md      

  - Comunidad:
      - community/index.md
      - Código de Conducta: community/code-of-conduct.md
      - Eventos: community/events.md

  - Este Manual: 
      - the-handbook/index.md
      - Contribuir: the-handbook/contribute.md

  - Insights:
      - insights/index.md
      - Evolución Digital: insights/evolucion-digital.md
