# Project information
site_name: Nuestro Manual
site_author: 23people.io
site_description: Nuestro manual público de lo que hacemos en 23people
strict: false
site_url: https://23people.io/

# Repository
repo_name: 23people/handbook
repo_url: https://github.com/23people-io/23people-handbook
edit_uri: edit/main/docs/

# Copyright
copyright: Copyright &copy; 2024 <a href="https://23people.io">23people SpA</a>

# Configuration
docs_dir: "docs"
site_dir: "site"
theme:
  name: "material"
  palette:
    - media: "(prefers-color-scheme)"
      scheme: default
      primary: pink
      accent: pink
      toggle:
        icon: material/lightbulb
        name: "Switch to light mode"
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: pink
      accent: pink
      toggle:
        icon: material/lightbulb-outline
        name: "Switch to dark mode"
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: pink
      accent: pink
      toggle:
        icon: material/lightbulb-auto-outline
        name: "Switch to system preference"
  features:
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
    - announce.dismiss
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.path
    - navigation.top
    - navigation.tracking
    - navigation.sections
    - search.suggest
    - search.share
    - toc.follow
    - content.action.view
  font:
    text: Roboto
    code: Roboto Mono
  logo: "https://23people.io/img/logo-white.svg"
  icon:
    repo: fontawesome/brands/github
  language: es

# Plugins
plugins:
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - "mkdocs-version-annotations":
      version_added_admonition: "tip"
  - mkdocstrings:
      enable_inventory: true
      handlers:
        python:
          options:
            docstring_style: google
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
  - git-committers:
      repository: 23people-io/23people-handbook
      branch: main
      token: !ENV ["MKDOCS_GIT_COMMITTERS_APIKEY"]

markdown_extensions:
  - pymdownx.highlight:
      linenums: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.details
  - pymdownx.snippets:
      restrict_base_path: false
  - admonition
  - tables
  - toc:
      permalink: true
      toc_depth: 2
  - attr_list
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/23people-io
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/9192215
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/23people.io/
    - icon: fontawesome/brands/tiktok
      link: https://www.tiktok.com/@23people.io
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/23people
  chatbot:
    url: https://2prxfnwkygf4vexczrbpcq.streamlit.app/?embed=true
nav:
  - Inicio:
      - Bienvenidos a 23people: index.md
      - Nuestras Metas: about-us/goals.md
      - Cultura:
          - Valores: about-us/values.md
          - Prácticas: practices/index.md
      - Servicios: about-us/services.md
      - Métricas: about-us/metrics.md
      - Nuestra Historia: about-us/history.md

  - "Organización":
      - organization/index.md
      - Equipos:
          - "IT Talent Services":
              - "Acerca de": organization/teams/it-talent-services/index.md
              - "Data & Analytics": organization/teams/it-talent-services/data-analytics/index.md
              - "Glosario": organization/teams/it-talent-services/glosario.md
          - "Digital Platforms, Data & AI Services":
              - functions/digital-platforms-services/index.md
              - "KPIs y Métricas": functions/digital-platforms-services/kpis-and-metrics/index.md
          - "Jarvis":
              - organization/teams/jarvis/index.md
              - "Data & Analytics": organization/teams/jarvis/data-analytics/index.md
      - Funciones:
          - "People Growth":
              - organization/functions/people-growth/index.md
              - "Data & Analytics": organization/functions/people-growth/data-analytics/index.md
          - "Marketing & Sales":
              - organization/functions/marketing/index.md
              - "Data & Analytics": organization/functions/marketing/data-analytics/index.md
              - "Glosario": organization/functions/marketing/glosario.md
          - "Finances":
              - organization/functions/finances/index.md
          - "Engineering":
              - organization/functions/engineering/index.md

  - "Comunidad":
      - community/index.md
      - Código de Conducta: community/code-of-conduct.md
      - Eventos: community/events.md

  - "Prácticas":
      - practices/index.md

  - Acerca de este Manual: the-handbook/index.md
