# Project information
site_name: Nuestro Manual
site_author: 23people.io
site_description: Nuestro manual público de lo que hacemos en 23people
strict: false
site_url: https://23people.io/

# Repository
repo_name: 23people/handbook
repo_url: https://github.com/23people-io/23people-handbook
edit_uri: edit/main/docs/

# Copyright
copyright: Copyright &copy; 2024 <a href="https://23people.io">23people SpA</a>

# Configuration
docs_dir: "docs"
site_dir: "site"
theme:
  name: "material"
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: pink
      accent: pink
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: pink
      accent: pink
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
    - announce.dismiss
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.path
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - search.suggest
    - toc.follow
    - navigation.sections
    - content.action.edit
  font:
    text: Roboto
    code: Roboto Mono
  logo: "https://23people.io/img/logo-white.svg"
  icon:
    repo: fontawesome/brands/github
  language: es

# Plugins
plugins:
  - blog:
      post_dir: "{blog}/articles"
      post_date_format: long
      post_readtime: true
      authors: true
      authors_file: "{blog}/.authors.yml"
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - "mkdocs-version-annotations":
      version_added_admonition: "tip"
  - mkdocstrings:
      enable_inventory: true
      handlers:
        python:
          options:
            docstring_style: google

markdown_extensions:
  - pymdownx.highlight:
      linenums: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - pymdownx.snippets:
      restrict_base_path: false
  - admonition
  - tables
  - toc:
      permalink: "#"
  - attr_list
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/23people-io
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/9192215
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/23people.io/
    - icon: fontawesome/brands/tiktok
      link: https://www.tiktok.com/@23people.io
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/23people
  chatbot:
    url: https://2prxfnwkygf4vexczrbpcq.streamlit.app/?embed=true
  alternate:
    - name: "English"
      link: en/
      lang: en
    - name: "Español"
      link: es/
      lang: es
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
  status:
    wip: Work in progress

nav:
  - Home:
      - about-us/index.md
      - Nuestros valores: about-us/nuestros-valores.md
      - Nuestras metas: about-us/nuestras-metas.md
      - Nuestros servicios: about-us/nuestros-servicios.md
      - Nuestra organización: about-us/nuestra-organizacion.md
      - Acerca de este manual: handbook/index.md

  - Comunidad:
      - Comunidad:
          - community/index.md
          - Código de Conducta: community/code-of-conduct.md
          - Diversidad e Inclusión: community/diversity-and-inclusion.md
          - Eventos: community/events.md
          - Voluntariado: community/volunteering.md

  - Conocimiento:
      - "Flujos de Trabajo": knowledge/gestion-de-flujos-de-trabajo.md

  - Departamentos:
      - De Servicios:
          - "IT Talent Services":
              - "Acerca de": departments/it-talent-services/index.md
              - "KPIs y Métricas": departments/it-talent-services/kpis-and-metrics/index.md
              - "Glosario": departments/it-talent-services/glosario.md
          - "Digital Platforms, Data & AI":
              - Acerca de: departments/digital-platforms-services/index.md
              - "KPIs y Métricas": departments/digital-platforms-services/kpis-and-metrics/index.md
      - Funcionales:
          - People Growth:
              - Acerca de: departments/people-growth/index.md
              - "KPIs y Métricas": departments/people-growth/kpis/index.md
          - "Marketing & Strategic Growth":
              - Acerca de: departments/marketing/index.md
              - "KPIs y Métricas": departments/marketing/kpis-and-metrics/index.md
              - Glosario: departments/marketing/glosario.md
          - Finances:
              - departments/finances/index.md
          - Engineering:
              - departments/engineering/index.md

  - Blog:
      - blog/index.md
