name = "23p-handbook-knowledge-upserter"
compatibility_flags = ["nodejs_compat"]
main = "src/index.ts"
compatibility_date = "2025-01-01"

[observability]
enabled = true

[vars]
OPENAI_EMBEDDINGS_MODEL = "text-embedding-3-small"
OPENAI_EMBEDDINGS_DIMENSIONS = 768
OPENAI_EMBEDDINGS_API_ENDPOINT = "https://api.openai.com/v1/embeddings"
REPO_NAME = "23p-handbook"
REPO_OWNER = "23people-io"

[[queues.consumers]]
queue = "23p-docs-to-index-queue" # the name of the queue

# Bind the Workers AI model catalog. Run machine learning models, powered by serverless GPUs, on Cloudflare’s global network
# Docs: https://developers.cloudflare.com/workers/wrangler/configuration/#workers-ai
[ai]
binding = "AI" # available in your Worker on env.AI

# Bind a Vectorize index. Use to store and query vector embeddings for semantic search, classification and other vector search use-cases.
# Docs: https://developers.cloudflare.com/workers/wrangler/configuration/#vectorize-indexes
[[vectorize]]
binding = "HANDBOOK_VECTORIZE_INDEX_ID" # available in your Worker on env.HANDBOOK_VECTORIZE_INDEX_ID
index_name = "handbook-index" # the name of the index
