name: Handbook Vector Indexer Worker
on:
  push:
    branches:
      - main

jobs:
  vector-indexer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Process Docs
        uses: actions/script@v7
        with:
          script: |
            const branch = await github.rest.repos.getBranch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              branch: `main`
            });
            console.log(branch.data);
