name: Handbook Vector Indexer Worker
on:
  push:
    branches:
      - main

jobs:
  vector-indexer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: main

      - uses: actions/github-script@v7
        with:
          script: |
            sparse-checkout: |
              docs
