name: Handbook Vector Indexer Worker
on:
  push:
    branches:
      - main

jobs:
  vector-indexer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: docs
