name: 23people-company-handbook

on:
  push:
    branches: 
      - stage

jobs:
  build:
    runs-on: ubuntu-latest
    environment: stage
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key

      - name: Add server to known hosts
        run: |
          ssh-keyscan -H ${{ secrets.IP_SERVER }} >> ~/.ssh/known_hosts
          echo "Done"

      - name: Deploy code via SSH
        run: |
          ssh -i ~/.ssh/deploy_key ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} '
            mkdir -p ${{ vars.WORKDIR }} &&
            cd ${{ vars.WORKDIR }} &&
            if [ -d ".git" ]; then
              git pull origin ${{ github.ref_name }};
            else
              git clone --branch ${{ github.ref_name }} git@github.com-${{ github.event.repository.name }}:${{github.repository}}.git .;
            fi
          '
      - name: Install dependencies
        run: |
          ssh -i ~/.ssh/deploy_key ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} '
            cd ${{ vars.WORKDIR }} &&
            /home/jedi/.local/bin/poetry install --no-root &&
            export PYTHONPATH=./src
          '
      - name: Restart pm2
        run: |
          ssh -i ~/.ssh/deploy_key ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} '
            cd ${{ vars.WORKDIR }} &&
            source ~/.nvm/nvm.sh &&
            pm2 restart run-pm2-${{ github.ref_name }}.json
          '
        
